Changes
Cratis/ApplicationModel pull request #33
Opened 2024-06-21 21:02 UTC by woksin

## Summary

Lots of changes ...

### Added

- Describe the added features

### Changed

- Describe the outwards facing code change

### Fixed

- Describe the fix and the bug

### Removed

- Describe what was removed and why

### Security

- Describe the security issue and the fix

### Deprecated

- Describe the part of the code being deprecated and why

2024-06-21 21:03 UTC, woksin commented
@einari For some damn reason I cannot get 403 in the Sample and I have no idea why 😢 Lots of things has changed though, however I cannot understand why that would be impacted

2024-06-22 07:09 UTC, woksin commented
@einari there some thing I'd like to figure out.

- Are these packages dependent on rach other in a way. I.e does your application need to do UseCratisApplicationModel when you also UseCratisMongoDB? If so maybe look at a more unified model for building the configurations?
- How the ModelNameResolver and ModelNameConvention classes and ioc hookups are meant to be used was a bit confusing to me. This also will depend on wheter or not we should allow to have differen model name conventions in the same application (for some reason). And if not, it would be niced if you could choose that explicitly in the configuration process of the ApplicationModel(?)

2024-06-22 08:34 UTC, einari commented
1. The base Applications package is independent of MongoDB and Orleans packages, don't see the need for changing that and create a dependency hierarchy. Then its possible to get value just from the MongoDB stuff on its own for instance, without it having to have any of the hook up for ASP.NET. We should also consider having `IHostBuilder` extensions for configuring these as well, to allow them to be used in non ASP.NET Core projects.
2. For now we just keep this simple till there is a requirement. One resolver and convention per process. Lets build things out as requirements come in, not pre-empting things.

2024-06-22 08:40 UTC, woksin commented
for the model name convention  and resolver I think my main issue was that the Cratis MongoDB framework depends on using it, so the hookup of it if you want any other convention than the default one should be a part of the setup for CratisMongoDB, if that made sense

2024-06-24 07:53 UTC, woksin commented
@einari So how did we want to do the model name convention / resolver stuff here? 😄

2024-06-24 08:46 UTC, einari requested changes

2024-06-24 08:46 UTC, einari commented on Source/DotNET/MongoDB/DatabaseExtensions.cs
> +    internal static IModelNameResolver? ModelNameResolver;
Suggest we make this a property, not nullable, with a private nullable field.
On the get we would throw the exception `MongoDatabaseNameResolverNotConfigured`that gives the dev a heads up what is wrong and what to do.

2024-06-24 08:46 UTC, einari commented on Source/DotNET/MongoDB/MongoDBBuilder.cs
> +    public IModelNameConvention? ModelNameConvention { get; set; } = new DefaultModelNameConvention();
We only need to bind to a type (the next property) and not an instance.

2024-06-24 08:46 UTC, einari commented on Source/DotNET/MongoDB/HostBuilderExtensions.cs
> +        services.AddSingleton<IModelNameConvention>(provider =>
Bind directly to the type `ModelNameConventionType` and not try to instantiate it, as we want the IoC to do this.

2024-06-24 08:46 UTC, einari commented on Source/DotNET/MongoDB/HostBuilderExtensions.cs
> +        services.AddSingleton<IModelNameResolver, ModelNameResolver>();
Suggest we make this configurable as well, but default to the `ModelNameResolver`.

2024-06-24 08:46 UTC, einari commented on Source/DotNET/MongoDB/MongoCollectionAdapter.cs
> +        _collection = database.GetCollection<T>(GetReadModelName(typeof(T)));
Lets switch to using the extension method in `DatabaseExtensions` for getting collection, and remove the dependency to `IModelNameResolver`.
The default `ModelNameResolver` does what the `GetReadModelName()` private method already does.

2024-06-24 08:46 UTC, einari commented on Source/DotNET/MongoDB/MongoCollectionAdapter.cs
>      string GetReadModelName(Type readModelType)
Remove this method.

2024-06-24 08:46 UTC, einari commented on Source/DotNET/MongoDB/MongoDatabaseNameResolverNotConfigured.cs
> +    : Exception($"A resolver for MongoDB database names has not been configured. {message}")
Lets keep the original message, as we then guide developers to the path of success.

2024-06-24 08:46 UTC, einari commented on Specifications/MongoDB/Resilience/for_MongoCollectionInterceptor/given/an_interceptor.cs
> +using Cratis.Applications.MongoDB.Resilience;
Lets fix the namespace for the Specs instead. Add the `.Applications` in all the specs.

2024-06-24 09:42 UTC, woksin commented on Source/DotNET/MongoDB/DatabaseExtensions.cs
> +    internal static IModelNameResolver? ModelNameResolver;
What do you mean with property? It need to be a static, since the class is static. Do you mean public property with only a getter and a private nullable field with an internal setter? Or what do you mean?

2024-06-24 09:47 UTC, woksin commented on Source/DotNET/MongoDB/DatabaseExtensions.cs
> +    internal static IModelNameResolver? ModelNameResolver;
> Suggest we make this a property, not nullable, with a private nullable field. On the get we would throw the exception `MongoDatabaseNameResolverNotConfigured`that gives the dev a heads up what is wrong and what to do.

`MongoDatabaseNameResolverNotConfigured` is not the right exception because this is the name of the resolved collection, not the database.

2024-06-24 09:53 UTC, einari commented on Source/DotNET/MongoDB/DatabaseExtensions.cs
> +    internal static IModelNameResolver? ModelNameResolver;
👍🏻 Makes sense. `ModelNameResolverNotConfigured` sounds good.

2024-06-24 09:53 UTC, woksin commented on Source/DotNET/MongoDB/MongoDBBuilder.cs
> +    public IModelNameConvention? ModelNameConvention { get; set; } = new DefaultModelNameConvention();
No, as far as I understand that's not entirely right. For instance if you want to use the `NamespacedModelNameConvention` which has a constructor that you can give parameters to in order to configure how it uses the namespace to resolve the name you might want to give it a specific instance of an implementation and not just the type to rely on the IoC container to resolve it

2024-06-24 09:53 UTC, einari commented on Source/DotNET/MongoDB/DatabaseExtensions.cs
> +    internal static IModelNameResolver? ModelNameResolver;
And then add to the message information that guides the developer to the do the correct `Use...()` method.

2024-06-24 09:53 UTC, woksin commented on Source/DotNET/MongoDB/HostBuilderExtensions.cs
> +        services.AddSingleton<IModelNameConvention>(provider =>
Look at above comment https://github.com/Cratis/ApplicationModel/pull/33#discussion_r1650723386

2024-06-24 09:54 UTC, woksin commented on Source/DotNET/MongoDB/HostBuilderExtensions.cs
> +        services.AddSingleton<IModelNameResolver, ModelNameResolver>();
That's ecactly what this did, from my understandning :)

2024-06-24 09:55 UTC, einari commented on Source/DotNET/MongoDB/MongoDBBuilder.cs
> +    public IModelNameConvention? ModelNameConvention { get; set; } = new DefaultModelNameConvention();
Ahh... Of course.. That is true, I completely forgot. 
Lets keep both as you proposed and then default to the Default one. 
But validate if both are set and then throw an appropriate exception saying the developer has to choose one. 
`Ambiguous...Something` exception.

2024-06-24 09:55 UTC, woksin commented on Source/DotNET/MongoDB/MongoCollectionAdapter.cs
> +        _collection = database.GetCollection<T>(GetReadModelName(typeof(T)));
Sounds good 👍

2024-06-24 09:55 UTC, einari commented on Source/DotNET/MongoDB/HostBuilderExtensions.cs
> +        services.AddSingleton<IModelNameConvention>(provider =>
Ditto :)

2024-06-24 09:58 UTC, woksin commented on Source/DotNET/MongoDB/MongoDatabaseNameResolverNotConfigured.cs
> +    : Exception($"A resolver for MongoDB database names has not been configured. {message}")
But given the way it is used here it provided better guidance in terms of the output to the developer in my opinion? Look at the new `ThrowIfNotConfigured` method and signature below, now it takes in the Type? whcih can be either null or configured to a wrong Type which is not assignalble to the `IMongoServerResolver` interface, so there are two things that can be wrong here and then keeping the base text did not make sense in my opininon

2024-06-24 09:59 UTC, woksin commented on Specifications/MongoDB/Resilience/for_MongoCollectionInterceptor/given/an_interceptor.cs
> +using Cratis.Applications.MongoDB.Resilience;
Yes of course, that's a better solution 😄

2024-06-24 10:03 UTC, woksin commented on Source/DotNET/MongoDB/MongoDBBuilder.cs
> +    public IModelNameConvention? ModelNameConvention { get; set; } = new DefaultModelNameConvention();
I think that I dealt with this in an okay way:
![Screenshot 2024-06-24 at 12 01 35](https://github.com/Cratis/ApplicationModel/assets/13407188/d2ed8786-0aa7-4556-8a95-a4822679eeff)

But as you said I should probably validate that you're not doing anything weird in a manual way. Also the ModelNameConvention defaults to the default convention at the property. But I should probably add a check for it in the validator as well

2024-06-24 10:04 UTC, woksin commented on Source/DotNET/MongoDB/MongoDBBuilder.cs
> +    public IModelNameConvention? ModelNameConvention { get; set; } = new DefaultModelNameConvention();
So the ModelNameConvention property is optional, but the ***Type is not and dictates together with the instance property whether it should be resolved by the IoC or not

2024-06-24 10:06 UTC, woksin commented on Source/DotNET/MongoDB/DatabaseExtensions.cs
> +    internal static IModelNameResolver? ModelNameResolver;
But you did not answer the first comment, @einari https://github.com/Cratis/ApplicationModel/pull/33#discussion_r1650703026 🥹

2024-06-24 10:09 UTC, woksin commented on Source/DotNET/MongoDB/DatabaseExtensions.cs
> +    internal static IModelNameResolver? ModelNameResolver;
And also, this scenario where this hasn't been configured should never occur and is in that case an internal exception, since this is validated on the MongoDB builder. So I don't really see any value in changing any of this really?

2024-06-24 10:35 UTC, einari commented on Source/DotNET/MongoDB/MongoDatabaseNameResolverNotConfigured.cs
> +    : Exception($"A resolver for MongoDB database names has not been configured. {message}")
Excellent!   That is a good pattern and something we should do more of. Some exceptions has this. 
Sometimes its not possible to do it, but when it makes sense we should do that.

2024-06-24 10:37 UTC, einari commented on Source/DotNET/MongoDB/MongoDBBuilder.cs
> +    public IModelNameConvention? ModelNameConvention { get; set; } = new DefaultModelNameConvention();
You could make both optional, but one of them has to be set - and not both. 
If both are set, its ambiguous and can't be resolved. That gives you the opportunity to specify a convention that can be resolved using the IoC and one that you resolve yourself.

2024-06-24 13:28 UTC, woksin commented
@einari Now it should be better

2024-06-25 06:32 UTC, einari approved these changes

2024-06-25 06:32 UTC, merged